root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server/main.go"
  bin = "tmp/main"
  exclude_dir = ["vendor", "tmp", ".git"]
  exclude_file = []
  extensions = ["go", "toml", "html"]
  delay = 1000 # ms
  stop_on_error = true
  log = "build-errors.log"

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"