tunnel: ${TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: ${TUNNEL_DOMAIN}
    service: http://frontend:80
  - hostname: ${TUNNEL_API_DOMAIN}
    service: http://backend:8080
  # 兜底规则
  - service: http_status:404